meta_product_name: "Raros"
meta_title: "Raros - Conectando portadores de doenças raras."
meta_description: "Raros é mais que uma rede social, é a plataforma em que portadores de doenças raras se conectam para compartilhar informações, sentimentos e experiências."
meta_image: "meta.jpg" # should exist in `app/assets/images/`
